import { PetTypeEnum } from 'src/utils/enums';

export const ServiceTypesSeeder = [
  {
    id: 1,
    name: 'Boarding',
    displayName: 'Boarding',
    slug: 'boarding',
    description: 'Overnight pet care in your home',
    icon: 'sitter-home',
    active: true,
    location: 'provider_home',
    petType: PetTypeEnum['ANY'],
    browsable: true,
    start_date_selector_description: 'Drop-Off',
    end_date_selector_description: 'Pick-Up',
    appRequired: false,
    sequence: 1,
    unitlabel: 'night',
    meta: {
      'base-rate': 25,
      'cat-care': 0.7,
      'puppy-rate': 1.1,
      'holiday-rate': 1.2,
      'additional-cat': 0.45,
      'additional-dog': 0.8,
    },
  },
  {
    id: 2,
    name: 'House Sitting',
    displayName: 'House Sitting',
    slug: 'house-sitting',
    description: `Overnight pet care in your client's home`,
    icon: 'sitter-traveling',
    active: true,
    location: 'requester_home',
    petType: PetTypeEnum['ANY'],
    browsable: true,
    start_date_selector_description: 'When are you leaving?',
    end_date_selector_description: 'When are you returning?',
    appRequired: false,
    sequence: 2,
    unitlabel: 'night',
    meta: {
      'base-rate': 25,
      'cat-care': 0.7,
      'puppy-rate': 1.1,
      'holiday-rate': 1.2,
      'additional-cat': 0.35,
      'additional-dog': 0.6,
    },
  },
  {
    id: 3,
    name: 'Drop-In Visits',
    displayName: 'Drop-In Visits',
    slug: 'drop-in-visits',
    description: `Potty breaks and play dates`,
    icon: 'homevists',
    active: true,
    location: 'requester_home',
    petType: PetTypeEnum['ANY'],
    browsable: true,
    start_date_selector_description: 'When are you leaving?',
    end_date_selector_description: 'When are you returning?',
    appRequired: false,
    sequence: 3,
    unitlabel: 'visit',
    meta: {
      'base-rate': 25,
      'cat-care': 0.9,
      'puppy-rate': 1.1,
      'holiday-rate': 1.25,
      'additional-cat': 0.35,
      'additional-dog': 0.6,
      'sixty-minutes': 1.6,
    },
  },
  {
    id: 4,
    name: 'Day Care',
    displayName: 'Day Care',
    slug: 'doggy-day-care',
    description: `Daytime pet care in your home`,
    icon: 'daycare',
    active: true,
    location: 'provider_home',
    petType: PetTypeEnum['DOG'],
    browsable: true,
    start_date_selector_description: 'Drop off between',
    end_date_selector_description: 'Pick-up between',
    appRequired: false,
    sequence: 4,
    unitlabel: 'day',
    meta: {
      'base-rate': 25,
      'cat-care': 0.7,
      'puppy-rate': 1.1,
      'holiday-rate': 1.2,
      'additional-cat': 0.45,
      'additional-dog': 0.8,
    },
  },
  {
    id: 5,
    name: 'Pet Walking',
    displayName: 'Pet Walking',
    slug: 'dog-walking',
    description: `Pet walks that fit your schedule`,
    icon: 'walking',
    active: true,
    location: 'requester_home',
    petType: PetTypeEnum['ANY'],
    browsable: true,
    start_date_selector_description: '',
    end_date_selector_description: '',
    appRequired: false,
    sequence: 5,
    unitlabel: 'walk',
    meta: {
      'base-rate': 25,
      'cat-care': 0.9,
      'puppy-rate': 1.1,
      'holiday-rate': 1.25,
      'additional-cat': 0.35,
      'additional-dog': 0.6,
      'sixty-minutes': 1.6
    },
  },
];

export const ServiceUnitAndMeta = [];
