export const subscriptionPlanSeeder = [
  {
    name: 'basic',
    slug: 'basic',
    displayName: 'BASIC',
    monthlyRate: 0,
    annualRate: 0,
    details: 'Basic Plan',
    features: [
      'Unlimited appointments only at 9% service charge for each appointment.',
      'Free Service tracking for better sitters and owners engagement.',
      'Unlimited Text Messaging with owners.',
    ],
    sequence: 1,
    active: true,
  },
  {
    name: 'gold',
    slug: 'gold',
    displayName: 'GOLD',
    monthlyRate: 75,
    annualRate: 900,
    details: 'Gold Plan',
    features: [
      'Unlimited appointments only at 2% service charge for each appointment.',
      'Free Service tracking for better sitters and owners engagement.',
      'Unlimited Text Messaging with owners.',
      'Get Basic background check to get a basic verified badge.',
      'Dedicated Members for Support.',
      'Unlimited Video Messaging with owners for better engagement.',
    ],
    sequence: 2,
    active: true,
  },
  {
    name: 'platinum',
    slug: 'platinum',
    displayName: 'PLATINUM',
    monthlyRate: 149,
    annualRate: 1788,
    details: 'Platinum Plan',
    features: [
      'Unlimited appointments at 0% service charge for each appointment.',
      'Free Service tracking for better sitters and owners engagement.',
      'Unlimited Text Messaging with owners.',
      'Get Detailed background check to get a premium verified badge.',
      'Get Accidental and liability protection from the platform.',
      'Dedicated Members for Support.',
      'Get a Premium badge.',
      'Unlimited Video Messaging with owners for better engagement.',
    ],
    sequence: 3,
    active: true,
  },
];
