export enum APPOINTMENT_BILLING_STATES {
  CUSTOMER_PAID = 'CUSTOMER_PAID',
  FULL_REFUND = 'FULL_REFUND',
  PARTIAL_REFUND = 'PARTIAL_REFUND',
  PAID_OUT = 'PAID_OUT',
  LOCKED_BY_ADMIN = 'LOCKED_BY_ADMIN',
}

export enum APPOINTMENT_BILLING_NEXT_STATE {
  REFUNDING = 'REFUNDING',
  PARTIAL_REFUNDING = 'PARTIAL_REFUNDING',
  PREPARING_FOR_PAYOUT = 'PREPARING_FOR_PAYOUT',
  PAYING_OUT = 'PAYING_OUT',
  UPDATE_AFTER_PAYOUT = 'UPDATE_AFTER_PAYOUT',
  FINISHED = 'FINISHED',
}
